-- NorthPeak Ops v2 — CRM: clients, leads, jobs, activity log.
--
-- GENERATED by scripts/generate-crm-migration.ts. Edit src/lib/db/schema.ts
-- and re-run `npm run db:generate:crm`; src/lib/admin/crm.test.ts asserts
-- the two agree.
--
-- Additive only. 0000_northpeak_ops.sql is not edited and not replayed, and
-- every statement here is guarded so this migration can be applied to a
-- database that already has v1 data in it.
--
--   npm run db:push

CREATE TABLE IF NOT EXISTS "clients" (
  "id" serial PRIMARY KEY,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "name" text NOT NULL,
  "phone" text DEFAULT '' NOT NULL,
  "email" text,
  "address" text,
  "area" text DEFAULT '' NOT NULL,
  "source" text DEFAULT 'other' NOT NULL,
  "notes" text DEFAULT '' NOT NULL,
  "tags" jsonb DEFAULT '[]'::jsonb NOT NULL,
  "lifetime_value_cents" integer DEFAULT 0 NOT NULL,
  CONSTRAINT "clients_source_known" CHECK ("source" IN ('website_form', 'google', 'referral', 'repeat', 'ads', 'walk_in', 'other'))
);

CREATE TABLE IF NOT EXISTS "leads" (
  "id" serial PRIMARY KEY,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "client_id" integer REFERENCES "clients" ("id") ON DELETE SET NULL,
  "name" text NOT NULL,
  "phone" text DEFAULT '' NOT NULL,
  "email" text DEFAULT '' NOT NULL,
  "area" text DEFAULT '' NOT NULL,
  "source" text DEFAULT 'other' NOT NULL,
  "message" text DEFAULT '' NOT NULL,
  "status" text DEFAULT 'new' NOT NULL,
  "owner" text DEFAULT 'unassigned' NOT NULL,
  "next_follow_up_at" timestamp with time zone,
  "created_from" text DEFAULT 'manual' NOT NULL,
  "lost_reason" text,
  CONSTRAINT "leads_source_known" CHECK ("source" IN ('website_form', 'google', 'referral', 'repeat', 'ads', 'walk_in', 'other')),
  CONSTRAINT "leads_status_known" CHECK ("status" IN ('new', 'contacted', 'quoted', 'booked', 'won', 'lost')),
  CONSTRAINT "leads_owner_known" CHECK ("owner" IN ('Nima', 'Sina', 'unassigned')),
  CONSTRAINT "leads_origin_known" CHECK ("created_from" IN ('manual', 'website_form', 'quote'))
);

CREATE TABLE IF NOT EXISTS "jobs" (
  "id" serial PRIMARY KEY,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "client_id" integer REFERENCES "clients" ("id") ON DELETE SET NULL,
  "quote_id" integer REFERENCES "quotes" ("id") ON DELETE SET NULL,
  "scheduled_start" timestamp with time zone,
  "scheduled_end" timestamp with time zone,
  "assigned_to" text DEFAULT 'unassigned' NOT NULL,
  "status" text DEFAULT 'scheduled' NOT NULL,
  "address" text DEFAULT '' NOT NULL,
  "notes" text DEFAULT '' NOT NULL,
  "checklist" jsonb DEFAULT '[]'::jsonb NOT NULL,
  -- URLs only. Upload lands in v3; the columns exist now so it needs no
  -- migration of its own.
  "before_photos" jsonb,
  "after_photos" jsonb,
  CONSTRAINT "jobs_assignee_known" CHECK ("assigned_to" IN ('Nima', 'Sina', 'both', 'unassigned')),
  CONSTRAINT "jobs_status_known" CHECK ("status" IN ('scheduled', 'in_progress', 'done', 'cancelled'))
);

CREATE TABLE IF NOT EXISTS "activity_log" (
  "id" serial PRIMARY KEY,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "entity_type" text NOT NULL,
  "entity_id" integer NOT NULL,
  "actor" text NOT NULL,
  "kind" text NOT NULL,
  "body" text DEFAULT '' NOT NULL,
  CONSTRAINT "activity_entity_known" CHECK ("entity_type" IN ('lead', 'client', 'job', 'quote')),
  CONSTRAINT "activity_kind_known" CHECK ("kind" IN ('note', 'status_change', 'call', 'sms', 'system'))
);

-- Quotes gain their CRM links. Both nullable, so every row written by v1
-- stays valid exactly as it is.
ALTER TABLE "quotes" ADD COLUMN IF NOT EXISTS "client_id" integer;
ALTER TABLE "quotes" ADD COLUMN IF NOT EXISTS "job_id" integer;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'quotes_client_id_fk'
  ) THEN
    ALTER TABLE "quotes" ADD CONSTRAINT "quotes_client_id_fk"
      FOREIGN KEY ("client_id") REFERENCES "clients" ("id") ON DELETE SET NULL;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'quotes_job_id_fk'
  ) THEN
    ALTER TABLE "quotes" ADD CONSTRAINT "quotes_job_id_fk"
      FOREIGN KEY ("job_id") REFERENCES "jobs" ("id") ON DELETE SET NULL;
  END IF;
END $$;

-- The board reads by status, the calendar by date, and every timeline reads
-- an (entity_type, entity_id) pair.
CREATE INDEX IF NOT EXISTS "leads_status_idx" ON "leads" ("status");
CREATE INDEX IF NOT EXISTS "leads_owner_idx" ON "leads" ("owner");
CREATE INDEX IF NOT EXISTS "leads_follow_up_idx" ON "leads" ("next_follow_up_at");
CREATE INDEX IF NOT EXISTS "leads_created_at_idx" ON "leads" ("created_at" DESC);
CREATE INDEX IF NOT EXISTS "jobs_scheduled_start_idx" ON "jobs" ("scheduled_start");
CREATE INDEX IF NOT EXISTS "jobs_client_idx" ON "jobs" ("client_id");
CREATE INDEX IF NOT EXISTS "clients_name_idx" ON "clients" ("name");
CREATE INDEX IF NOT EXISTS "activity_entity_idx" ON "activity_log" ("entity_type", "entity_id", "created_at" DESC);
CREATE INDEX IF NOT EXISTS "quotes_client_idx" ON "quotes" ("client_id");
