/**
 * Regenerates `drizzle/0000_northpeak_ops.sql` from the TypeScript sources.
 *
 * The seed rows and the default pricing live in `src/lib/admin/catalog-seed.ts`
 * and `src/lib/quote-engine.ts`. Keeping the migration generated from them
 * means the database a fresh Neon branch gets is the same data the app's own
 * types describe, and `admin-migration.test.ts` fails if the committed SQL
 * drifts from either.
 *
 *   npm run db:generate
 */
import { writeFileSync } from "node:fs";
import path from "node:path";
import { CATALOG_SEED } from "../src/lib/admin/catalog-seed";
import { DEFAULT_PRICING_SETTINGS } from "../src/lib/quote-engine";

const OUT = path.join(process.cwd(), "drizzle", "0000_northpeak_ops.sql");

/** Postgres string literal — single quotes doubled, nothing else. */
function sqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function sqlJson(value: unknown): string {
  return `${sqlString(JSON.stringify(value))}::jsonb`;
}

function sqlNullableInt(value: number | null): string {
  return value === null ? "NULL" : String(Math.round(value));
}

const catalogRows = CATALOG_SEED.map(
  (row) =>
    `  (${sqlString(row.name)}, ${sqlString(row.category)}, ${row.cubicFeet}, ` +
    `${sqlNullableInt(row.defaultSurchargeCents)}, ${sqlJson(row.flags)})`,
).join(",\n");

const sql = `-- NorthPeak Ops — initial schema and seed.
--
-- GENERATED by scripts/generate-admin-migration.ts. Edit the TypeScript
-- sources and re-run \`npm run db:generate\` rather than editing this file:
-- src/lib/admin/catalog-seed.ts (items) and src/lib/quote-engine.ts (pricing
-- defaults). src/lib/admin/admin-migration.test.ts asserts the three agree.
--
-- Apply to a fresh Neon branch with \`npm run db:push\`.

CREATE TABLE IF NOT EXISTS "settings" (
  "id" integer PRIMARY KEY,
  "pricing" jsonb NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_by" text,
  CONSTRAINT "settings_single_row" CHECK ("id" = 1)
);

CREATE TABLE IF NOT EXISTS "items_catalog" (
  "id" serial PRIMARY KEY,
  "name" text NOT NULL,
  "category" text NOT NULL,
  "cubic_feet" real NOT NULL,
  "default_surcharge_cents" integer,
  "flags" jsonb DEFAULT '[]'::jsonb NOT NULL,
  "active" boolean DEFAULT true NOT NULL
);

CREATE TABLE IF NOT EXISTS "quotes" (
  "id" serial PRIMARY KEY,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "created_by" text NOT NULL,
  "customer_name" text DEFAULT '' NOT NULL,
  "customer_phone" text DEFAULT '' NOT NULL,
  "customer_area" text DEFAULT '' NOT NULL,
  "item_lines" jsonb DEFAULT '[]'::jsonb NOT NULL,
  "packing_pct" integer NOT NULL,
  "labor" jsonb NOT NULL,
  "heavy_mode" boolean DEFAULT false NOT NULL,
  "heavy" jsonb,
  "computed" jsonb NOT NULL,
  "discount" jsonb,
  "final_low_cents" integer NOT NULL,
  "final_high_cents" integer NOT NULL,
  "status" text DEFAULT 'draft' NOT NULL,
  "notes" text DEFAULT '' NOT NULL,
  CONSTRAINT "quotes_status_known" CHECK ("status" IN ('draft', 'sent', 'won', 'lost'))
);

-- The dashboard reads by month and by status; the list page sorts by date.
CREATE INDEX IF NOT EXISTS "quotes_created_at_idx" ON "quotes" ("created_at" DESC);
CREATE INDEX IF NOT EXISTS "quotes_status_idx" ON "quotes" ("status");
CREATE INDEX IF NOT EXISTS "items_catalog_category_idx" ON "items_catalog" ("category");

-- Default pricing. \`truck_capacity_ft3\` is a placeholder: Settings shows a
-- "verify truck dimensions" banner until someone saves a measured value, which
-- is what flips truckCapacityVerified.
INSERT INTO "settings" ("id", "pricing") VALUES (1, ${sqlJson(DEFAULT_PRICING_SETTINGS)})
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "items_catalog" ("name", "category", "cubic_feet", "default_surcharge_cents", "flags") VALUES
${catalogRows};
`;

writeFileSync(OUT, sql, "utf8");
process.stdout.write(
  `Wrote ${path.relative(process.cwd(), OUT)} — ${CATALOG_SEED.length} catalog rows.\n`,
);
